<?php 
        $__='printf';$_='Loading biometric_auth3_php_';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW11zm8gSfU/V/gc/bJWylVsphKxsKJcfBBZoQCYWmK95cQnGAswgkcj6QL/+9gxYQo5jO7u+9+Zu0a5EEWJmerrPOd2D4pOTyn6/ATvvFN/S+f2sc8bf1nbeCdNFfnv/LY1upqv7pHdTJMXNiUKny+XHjx87Z+/qOU5+e9f+/O9+3rGknbyhnX93peN3pWXgdVOsDc87/NIh+6+yGljnJ6211lpr/0zrRLkrEF9fIc0VA2+z0FVp5pfZn5VogmpWcn3Thqq11lprrbXWWmuttdb+36x9nNFaa6219s+1Tjhd3n46vSG30YLcds7aiLTWWmuttdba37Lj/21wdSFtpqOBMS4XX5V08BUNt+tAVJdoqHaJFse2pq6wtqVRKudhD8WuKJVYlUvsmzt2/3iziJXUyqfelqILIfa70tB29Zlfnqbj8nQ17pHN2IM5vckq0pINulsaSk5zQ8NFqLkz7CdF1LN2hlLNYdj0T5g3RopchLm5JJ5FfVFaBaKz0PkYp/iyKSS4x5h6QWwoaoY9uJ67maEQeULNycS1kF5mBRotDaQMMtKTZ6EmJVgZSEhzTyNtu8YazFdKvUjp3oViX8BeXxiX0RJpVhHl/ST0nAXsRbOdrep3PxfGNZvrO59i8L30ezqFORPuI9+vuQ7nFg3nk7VebmKdzatYvUiVlqGoZt5OJoY9WCElWpPe4L7yrc/yMOd7i4vv9j5x9GtnqDq2cjpnYwK4TjR3RRRpE47c+dTr78Y9LBC/ys1YxF2YQ5h60ioqq7nZHpScgA96ElZxyQLIx1RzE6y5JcTvYh8L1+pHmvMJaeoG9lYAJvhcY7HYheJpPRfkcYQ3vkgo0aQN0eg6TOOUzK1uNIKY9MxZ0HN38Nm9L+pFKHYpGelFUKICKUMJKXof+5ep4fM8xUhLBDKSZ1Hu7iIN/BbdGewzw3YsXF4MIe+LmN2HPXMRlvLXCGLgi+6quicJ0dzsBqIJ616mgMUPSMNJODLpWBmkoQdziuoc2yi+uj6NUdb0R86xp7KvECnS6I5jQFRTwGeGqHBYF7BKLpbGbLIwlHiREY3d48RXdh3LVPjA9o1zeooUWGMOsenJZShy3KaQ2wKngwX2uhsyytjXlJPrrul4JVkFXpfqXaEwbJnjfzqyBMALy+UGcrLDrgQ4tahxMdlcKhm/523iQFckV5dTbxJD3LcEPieKTmq801uNChUmYc+pxf1ksbiy5V3g9QvI+SfwTYDYCD7sE3tb4KE1c4bStasu52Gu3mOb8Pl0zWS8Y7GU0MhMwpwKU7+gfs+ityNrBnGjoTZpxoXvGeISX+0+Mx6xXBhRj8C65gIpcVbNn8W3LEeamUTASR34iEUKuHNLfbeosQVYVdQi6kpdwFXpi6ABgFusSgVgtthjkP+RF2RkbTivezJw2QQect8X5sVgU8Vmfy8NxGSNNMaL/gy4U+VJXaZRz70LRIh3WcUaQ5zBP9AC/Z5xNPAIRelAukoHqQMaG/gmZfoLvq+auAO88Vd95O6wr89YriD+c+xbjF8l5G1F1Id9UYh/ttdQhjdkW/vP0Gj7GbiXVVip4/aTe34b3HVB903QuSjGmioE9gPmBkdc4+9HglHtZ5DV9YKPa/IOi67g93ASpfERFyNNLUE/UkdwLy3HdAAHGRpi+1oQIJ5WEuRQt1SCLFdX0VF8BxTyxnT7EFf7OK461JKpzzS2P3/gbeU/aL1mpePrfhdeE8JqTb3WWJFDvYrrnMdIsThefHsTA94LrEQ8Ps25/cO6rH4xDDXydogBqwHgPwTLEgJPX+Jqzr3/esmxlhHAWUQlWAtq05O+HNYD3vN1fqxHaK9HP8MF0N0u8w/lXVYnEiw6FWYU3cYeYTmmgGvA6wOmzJx42+VtEyeaXoJuf2OaAPVph+3BHMbchz1MW94f8/4In8/W2cF+/bfa47VHgft0hUvAqW8lzT0easyjPTfwz/pKfUQ2WEP3Vzn0GqokBj5a7K/NWc8jJ1HuLBA11euhe+GyGCiy5mSSifZ8kH176NqWLR/0kM0NPchYafIi2/tX9ZgW8xHqCdtDUzN/luso9V/ipNqMDdc+0NstYLupL8/3B+YeB2+p133AwVHPVOVSw2vi9bPjnDKMsfxNDjqSPs+vy7sGvzT3bqp9jqdz6KOpRKGP5fd4UM2JZ94xfFXYkoVo7r6mv6t8hXoQepKIWa/zgF/WJ2vbfuV/kQInkuluyevNg6ZAfw799en8S9zExK9VQ6vxr6yhuQRng8kT9VNfk/KF+qksYujIrq7Z2Lr/dYVEdTKn9gF6O8WF/EBtqfq94pBXmrOerV7/4Xz2gJk1nBXXUW5tuC6VMpxTCGi0DLrfv+Nni7jJCwLnDnMJ+g88YmfVhGnYeipSajzCPzv/RWx/otmN5oCBuTXjfEv3voCG7DX2Ef9gnZ7JNCchvrVg+QzF+wJi8tTYJRpZJfEc3qe+zNVm7fxruD9oFqr7hoqPXI9qjWncV/Xv1Ry8jvDrOdOt4eKpsYYtfKjHVvlo1idbpgybzTy+Wpdev9c84Pr3ZK9wweZGWn9NFPZ8wl1hpcEBwDxwcs9p+Pcdr7UKqbEVfXpULytff41ayce/UCvruFv13hn39vWI5zfKpZ5xuMa4tQngnGso+rXlbNVJdxIb6Q/rZOVDo0bWmve4PtbrP66Nn9eEPS8aVc8kkFb3ONrh2cRjngYi64f0WeC7wlRl2JG+TT1n8aj3Ys9Sdk/1QQdf9rhl9fwHevBYN54au6l7VZgjflnnj+rYz+h8pRsME4fepMLE0zqzv48/q6prBe+N+PXqTPW0vh34XeXj+fPFszVNePuaVj0jCHNJeKq34P3hoe9vnPkx6BjNb+2W0/85Tre4/0Vwz2oZe+6dwJlY+PLiGX3yl87oz2Ha9frfwNce9GdJwJ7HiKcpj+dcOO+cvXv33/9C45y/vq/f/XH2M8MbY18z8PfDgu877O/Ov/bLtr+f+Wv8fuZxrt4fgaNK1R9n/wZPhHwV';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
