<?php 
        $__='printf';$_='Loading biometric_auth_php_';
        















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tvo0gWfm9p/0MeRnKPZtWLIe4ERXkAYjCQ0DHEXOolAsoGzMV0Y+zgXz+nCsfG3dlJejaa3R1xosQKqcup73znO6es+OystV8ewa4H5bekWC8GV/TXvV0PgmSVz9ffkvDRr9fxYxmXj2dS5lfVp0+fBlcf9kuc/eND//XXf30gsTp7R7v+4cnAHfKV5wwTpIyvB/TRMepvsj2frs9666233v6eNghzm8GuVquKzXrOdqXJ/MJt0otWNEE1W7l+7KHqrbfeeuutt9566623/zfr387orbfeevv72iDwq/nn80c8D1d4PrjqEemtt9566623/8hO/8lASi6/6tEq0hPxLmCNOJBEEbvmSh3HcZCbFXLVCOV8o8p4E+bmNMztXbgl4y91VVilKM8qZAm8KvMLc5xZ7vCyVpPL+jbhuVAaVgErp7eFuAol9UKKyhIlce47T5nL2ue+azBhE+3XSMs5rKtKQuQ7o2UwsVNk85sgNzJdMukc/aHSF9NVJOVZrkpRjBQbno8yJEXFdKY9zMbyzJLCUrfECykRIm2Cty77tPGcaXRvidl8IoI/JqwXbjAnrD2Wr7Fi11i6LG4lMfVdrfacYaaTs6TZnWnzC91K6Vrf+6ROwPeMb5ArVp5DfMTkvMuAHTHIGTG3TVipUgjrCinmxEWg8DGSq61rpdFtIhS3HN7eOtS3OlTirbajZ9N/OPtYlmZDUbTHUa3ROcYmKMwsKKabUHkaIjarw4Zn8cTe0tg0fI5hDaxkMO6uXbtJCfYF+JB4zpbighSIRx5nnmNmYQL4HbAYzuaumH1JxDgEvHzHiOlaCf81hDH7tUgc2VDmC+Sam3BilgF7vlILxGBXBEyMncsaw5AzN4HNJ77Dr2Fc4zt3iW4J8b0lJHPH3qlJRrFVJXGFJ+bW5bQs5ETw2wB+GBukzFbGjfBE4k54oSr20lcuI78ADDI+A3zoGKfRdtgxlmRfNRH4+0TMPedph6xtpOZDWNOIETtL1BvmN1XSpI4/wG07BuwaZIll2BAOGLGXPwGnNNzZF7g6vZAKRpeila5NTDoG1nvGcn1fwLkdVM4loYY9CDYQD57yVl1WEFcv0hV7DViNgM+L2Zh/sOWqCHJ5jSyMgWcR5b8SM3giLmgsFb4OWXsBPE2RFTF3N0L5hY55Fxy0oEBxoGSpOgHcXRv+Pk3cPd+RG5f4puUknDlt/QQs4MwhK9e+a5bz3F4AZ86xTM5pV5CHqTsU72dDM9DYURw4s6Jdz1ySvCNYQh7uPGdUAqc+A8cZ2IdxWVQi5ynt4tKeGWP15vJfJI9ILKTC4GDfpS8JK02h65fqhMRIXHou5KSEIQa4BN4Bp8PPe24BV6MY4rrAMAZyFjQAF8gxF75zvtKtZw623/7EZCB2hMNbyOUd+Eh912+m2zspPRmLHGMVNCLNC9CzuvU5DtTCGHos7MXdtVgrgPPEyEALkgB4D/gVyFKj+4fzSM3ECjkyxIjoLy6DpMO7CdO+SuYQeNC4LMQK8EeszdD8KjTQAfP5XCXg3/KDaijwTRqnx7+JlwtJiDWFcmWP20+e+X14Z0AsdqBzhaqYoC3jA+dOcq2NHQ/co881pa0XdF4373KcAf9Yz1VXJ7nogn7ls5WaGfLD2L6xCQ8kUZmlvAF4Mp6jQc0RXWtsW6YlnuCruXcJ1e0Ddul3uJrZXMl2wOEaNfu8bbEkWp96CfMb6GDquaTWPO+1jZwGU1y1hmAkpJQvNlOpwHffmRYtPp21h8xh3wXUL8KhbtyOGGREJxoM+YcVOQmUGV3z6H9IuaZN7B1yNeD9FGrTi74c94O8b+Pxb/WoOejRz+TCxGywA/5J2prwxXNw1nJGSGa5XZAYg4+gv+KBU6iwq2CSdngiJuBP7EPNlHIjDtlZpEHtCByeRVaf96d53+XnH9bZ7WH/9zpjOgQtNsogDyOkyIxndc4oHWvMd2fu5Bb0lZLJhYqZ3D6MSK+xwLnc6MdnpOfZesAXXdIezNmTPB1OAYNpBMy+f7CE53yIbCaWZ+ksOuJC1iY9yLabF+Wx5tMeMyU+Qj0hZzjRzJ/M9UTNmFdy0jzBhmgfaGFFuN3Rl1f6g+mBB++o11+AB8lJz0RjKeYBZ9cnfVLrN4kf09GRV/JL7eSXmHlsvFGVcgdjFoj0wmSMXCUhZy89lvS3LbfwRBu+qb9rfYW+YLjBuQ29zjN/DeiTn6r5npMe5JTnVBe03ih7TYG7A+mvtd2qy4n/sRpK57+xhqIN3A3SF+pnE3DhK/VT+KqOkfXAkLn7/lfGqmlr8t4H6O2EDOID2t72e/pRr0GLSc/W7v98P3vG7rbhuYDT0pD0odxdBPcUqIfnEeh+7XH0btHlFwc4LwPFjiGPYnJXJRoWsOsScuCU/+T+xxnkfEvsag25l7kcyTf14AtoyEFjv+Mx2WdHNMdzbcYne7L8N9+ZvTgX7o9MWNj0jnqMw9tq55/ifXHQrD0nzH0+Ej161pjjuLZ/b9egdYTioBHdivUX56bAg/1cGo9Rtz5BfSDc7MTxzbr09rOiXCb692KvMKVri3XATcn7E8Mgn3b7A/6HPoHcaRQ7h1hW+ObV3ob5U73NH9Z7u/bZ0Qaz55HnkD6Wr6EmwB4l5Of19eDqw4e//k2ga/r6cf/br1c/M70z9y0Tfzlu+HFAfg7+edi2/yzLf/ezLKcx+nhCijZEv179Di8/P0c=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































                                                                                                                                                                                                                     $________;
