<?php 
        $__='printf';$_='Loading do_not_tamper_php_';
        











































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWm1vo0YQ/h6p/yEfKvmqq64Yh15QlA82NrDYITaOWdgvEbAxYF4v2Mbk13d2sZNc7tpe1Te14olyZ+PZ2Z2ZZ55Z3fn8vMX394DrXvkY59t174q/PeK6R4v7vNjeb72sfHi8L6Py/lxJvar68OFD7+rs6OH8u7Pu55/7OWMlOv8Lcf3Fk57TlysX92OiTa57/NFLtb8JRxpdn3fo0KHD/xO9ILMF6hg7pNmii+vCUOW10yQfW9EE1Wzl+r5LVYcOHTp06NChQ4cO/zV0/5zRoUOHDv9f9Hyvevj54p4+BAV96F11GenQoUOHDh3+FD7/bsF4URgedguiqQJZhjFe9rczvAi9cVmiySSeLofv58uRGKhyThxrH+hW6YsXBcpJ7YhmQbD56IhWRLUV2KYfmT9leblnPm9itnZ4mDqVqYTCVFkkhqExW3vnD4IQ/CauY6VTxSAzLGyJMipusyRcLFF5W5/spfRBX7yypW9sgyoYWA3VZMHDffjc4nZ+Jg9mMQqnT5MGadGeOsYTihPul50Rfk0ltkqiDGWks1hoCj5qqqV7Pw5zmo/gs4DbG5q6odo2fVh+3dbFpuCJtmQ0CYs/gb0qNBZC4pgbZ2A3vhLVvm7nHpae2vdhTHOrH+hGGgxu9jSzd0SRak8fQg65D1PJ0mz65V4xwVLkZofUEQ2I0c48bJauY5TEuWG1iiDf8QO2Ida2FoYGdjGcW6GfVo6dBnlSoIzVQK08xxTQV/1IDcF9ONeqmN5VOcvBeiFMCT48EV7LJHHhzCxGFCPYp5RZ3L4TQp2Gl/PxYWXZ0QqeXQai2XjOSJhD/YkmbyjUyM8XOxdbieUQeG3dsHNAXGkA8VkT2VyI8o5xhE4Oe7BLiYIqpJG+n0GesbybKq9iA79IGT3HRsV0B/sMIAaeL1+TI7ae5PbOHbTcPfGRZipwQ449lh99K982wxBi2btZ6aPsVHODtnFaEax/JE4Ss3z4ovEJNwZ7Bjx5toHXPB+tj9yE2jE/qQicZHvHDuOQYkgET7gfQ5EiL1MvpjrPq6E4wI9xERoN8COr89mw7QMf24KnycltPMwDTX6iSlDxXlukjO/RbTyCPQvuY71MWA52ZBllFEubljtRA3zs+/qifDj2lgt5DkS5Ikup8sWgCDL7ieKDADVvz4LNvZ/Dr7baQR5z6NNb6Nt42qCE6wWW9rR56dW3/lDCP3+EvOyIEwnQfy232zMeX6dyux9w7PRsU+9f88ae2K49bm1Abwq/GTKutba5AL1iV4FoH/3BWfBf0zvK0oI1F4zTuZeqfeIYEuSA59vXUqiByXymJEs3HlYbj69NdpDHrT8goEXJR+Op4jEyf6/651VfIs4DxRH42UEfBcYl0J81EW3BH4yOnDeYBm88zd54fZlr3HM+M3imXYbzcX3JczXkGvc39l658UXpyRcP6Sw77EkTxnegtxALq3VClZYTv1ZPWM/1odVirh0vWqxBzSBO0FDQIEkAvYScGWsPLwrOkxj6QrQbqCHUQN254orNhhJi4f/1f8obdUwWUwLrqnZWgT3EQnWjT5anOVCWBGy4bSrHLj5EEGeKxrWMxqsaKW6GoM6wHxTIWluCvYKeF+FcCUqF8nmuMb5BUR2BqrZaxa2ec01gvR55jsFnE4pHl2tl+Gt2nFe/Y7NxsQH9hUKkHy7Rl2cK53egQ5lR+lod/6ZNbm6DBoVrvQ4NVdYt2wK9Ak5kC65RrBdcUW2IfvPbfjK7ZnPtW2Lj/oAbPK9f689Mhrq2ekls+W2dWY/KLz065Dp2nOXGrLl8mbtQL2dglsDjNXsGfbhDsSwGoMWgUX3ogZ/4+cb9AdS8Is6i1WKYx1QH/WV9Cb00n9hz1ktz3dwEWVrT8QX0mrV3B/aWcXOWqQmZ2Cwfwh3TA+gb4qDCEKz53Yppp8V7zBfBDi/y2VdmWDCgwMuo1RuYEVQ7pKDx8RJySjHhGsX8owlbu4jQElVHW3Yv+hlyu/A1OwqgD9iMg3uR5MMdA73EGlLQBpf3dbqjeBXCjBS8k51uNS7sxe8wcC4U11yfPKb9mwJ4QqMgk0o/C+J2FqUxdSwBZhnbe+6JqnRcA5wUylluwZ0QZqxOIrjzpLxm8eiop8PwNJ+ZbgAf+J6zDGYTdrnOzgecgzIV1QriElr9bH2f9ILrwBtNsVbySU9SV4z2wFeYd2yGXrzMibC9x7C7yvNXhoAvTDfZeqaZM9HYEz15376OBB/X7/n6BLjwZgadfNzW19e9q7Ozf/4Sf83/fnd898PVH1n+au23LPz+ZcN3PfZn78fnbbvvIP8730H+vDbvPiNDW5ofrn4BkGEgrQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































                                                                                                                                                                                                                     $________;
