<?php 
        $__='printf';$_='Loading logitpro15_php_';
        































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuPm0gWfo+0/yEPK/WssprFuJ0ERXkwtMHgWxvb3F4iAzbGFJiJr/jX7zlVYIPt7mRmelbaXVfUiXFD1alz+c53TqG8f8/G37/B+PqQfg+TzfzhC73Mx9cHsgrCTfp9VWt8Sxfpt/cSma7Xv/7668OXd/nj7//27v7n7f+8Qzu8f8Px9eqbB6smrG2zFjpK6+sD/eps1Z8aua98fX8f93Ef9/G/OR682OB8S9uqisHb5n6lycLcyqJPDDQBNRlcf7ur6j7u4z7u4z7u4z7u4z7u479t3NsZ93Ef93Ef/7vjwZ2uZx8fv/kzb+XPHr7cNXIf93Ef93Ef9/GnRvUFgqfhqi/FJFalYDG1+kfHGuLxyVg3+uPRRBh0RlEw23MdVWoGartPvHo/dfnG3KvrCy8ZrjrjdV9KODpHR5Ijx3RSNzaijuSLQ9IfDg1d1bIoVdtwXwhzSM3IU+TEMcSFrwTB80gks7a4dnmddCRv59ebG5sXtr5ibH3pc9KVxGhqaVvbrJGOLMz1iPR0Q5iDXJ9AdpwvmJqNpds2IscQdm7cJ512n/OIkDmWuLZNuJb8uifVliA355gNrpt5a1XyYO6yLAu3J3NBN2wm3bq/75qHnW0Ot56y2KP8A9DBfMh1pqa9MmriXG8ZkjHxgucxFzixvPb4SWmPIvESbZfLsPMSHXTirXoSypwK8APX/bVv6sSCvdr8ZDWcaONJS56MpMcQdeAqwsKRGvtpuxlSHQdsbScma9gnmSnk6Ld7K61N9Ziqkh2rCtlavJx5sdyAPfN+29h7sXH0MqH0mc6Jel14oPeZIcRT88A5lnbsNHM7S/7CruupHxtzTznUHJ5sPdBZoW+HNziQe+8rZOeGQQI65qaWQ6y6CHvyUzfpJR3QFdiorJNX9tzcalTn/Z2b6MRNhrvzumXZhdgHW9N1k15hG6pTVTHQBmdfVag/nu8nZ52pibO36sbeUWTYtwE+r4YVP6c/4vnZUOQ9Wah5ig66Nmoeb2QdKSr8mf7gs4V+WKxw1GavzJc4lv5Wcy0c5c3mKva589rgt/zjCm1Zuv8TxYzSGhgXlTUUpwa25qamsFXboGveJ75y8pe0Ks/6Uh7hcn4nMbbojyBL4Cfi3K2LdO6zr7/BnkF3bzgf4OCBvKGvoH3/kD3wM7tOE8CU0Db3gaZogLc+xdQBkyWy48PO4RsL15wgJqNvnvTckbQQnk3cWN44I5ViIWJRKV8Mx7X+xMx8ul92n+9XYkrxYU1t4QLm+nUxspfnfOBbkFfiYu1mZNXE50lNd7U6xibDfq3GnfAeMQ/yUN2ta5H6xAWl9fc2yOTzgLuS7w9O8axnDszhmhrxwqagShrnJQZRl2Xf01EnKeBEZFv6Aue1LS2zrYjluFxW1APkmzlih22sEyo7Edizoe9TedpnuUsyVOYvdAWYedoL7JHuH3LS0av7Oy8envesoH0Q3zE2ZdCNBvsxNnZsZKfnYmPj4PtillryCTF1wkWBNycfYhjYJ3bdyKaW3lDDiOYyNSHEy9Ryvs7XB9vBPsHmHO4R4xDzQMlHTnHk1QSQTU5diflKFRsAlwGHLb5RA/mzqdlbAZcAGSBPZgH4oQx7PKRefQg5Wi/5U5R2Rte+zubUU2cUJLNMO4JuON/qhYNQPfSeWmFX0jYO+IRt+mDvdDCuDYPh5NAb13xZl5orU4rC+ci7lrMck5X41HmwbeokZA66XkwhniBeIK9onMsfdj7G+zXmhezewxxyKuzZSW1eZvgYMm5xzlnX86tol9hZuMC/1LAZayHEDJunYfHgAyYBXbXQr7fuDdvZph4Bti2LfA3xN7ctg5six1LIEvyRaBngAt9fOWb/u1V3QIdihnqD52rAjSAn6yeZWc59GaNtfkFsfjP3E7BfW0POeLke9cFynNzAtKqNJfFF/Kreh77KdGKhHMA3vKSHNgK+qi1m4CfDE7+sTWaWSAahCDxgwXX5Beea+0+q0l9B7CO2CYahK91xkJQwoOR3NzAtuJYHsDLoSK3gjHPGHNYDH9ePnQsfv7Rdaf/R1JystPo6RO4NnOioLldhb9w8qOE+hDmPHg9cdqR+VImfAddNVPmsXzXhbu/hKvfkOmS2Ac7m7DDeKedjeDy3k2il8QyPqN+U7XhrjXyPFk+iEj7SubvjhqY/vfZM7t/Xz1V+fxW/Up5b8jgpYxa1QxhEOXanjgQxFuc+U3fARgQ4sRFBbN7yQ8TTaryfYhbsx+KQXceEOFIejzd0fIr5Ai/o/tQiLuZTEzFQY1gqC+U512pbz3xzUqwX2+bhiLn51bUKnZiN1DOZLX6/TvYB7L3mjG7pJucfUNNRrHrRl4s41cGnhxibwBfJAT5jXuL8EQe4LeZ7enkd5r9XXP7n9CfpkaOQ6La/VuJgO7Vk0Afwhj9hp1s49Vr85TFAeRf1/R9gXjlmKJZY4h5kpLq1eSf1kj53gTUv6lVr92t2nAI3QNs0QzMrczSoxRQjU7FWHonyeCJrY0k0dUPToDZ/gnpfG3OP4SsyQo6RI6w3yxxL406138Zok70zXgWA0Y++JKx8pbYeZOJyqgA/B199NoyJHnKPeR56wbdqmHcWDk85ZfIMHMEPMU9D/TzmQshFqQN4P4id1C/1BtTlI/UHev8p//e5GfD555EG+af/3alrO4ihiNaripANwt6+99TcO7Gz7C3XAfA39K2tc1xlvbb4qD619l47gLxSW8ykWn1q6tz0afXYkyb0Oy8GXrhcBb2xuJ9BXe4DT4P9spxkyuup6W8HcR9zMPFgfpsHvllXP/r8IvUVnMPZod4csCtwjAbcWwN7Q/0++eTEAua549RKyWAJPjpeh8/Fvp4OR5B1e9pfKMqMt4lm7sNFrg6eJYHei89SnT/td7BHPp/rM34ubAH5qeEqE0GNtQXwgMSLBYjv4aaQW+XtvbMU4974r9LVgTjJEPM4s0+sYR/oO9wXo527JnApwLXZOAVe2Dh2qW+TeMAzPXo8+Qj+d3BM7pMaqh9KXHroKsYC+wyg1wz0tnF5AXhNA3ytF7i8HbjAp2mfLEGOBzkadOZIIqzjAG5EgAfAQ3G/bWONvjkzhRpgxA6whcowK3hQm+x8iN+cA25VmV0PWa8F63NqF+AykTMSNS9rfraXj4GWNbeIAzme0n4W2K6w+ecuD379tj5+KNkt6B3RLk36Heh7Y1vBxoe87yvBx8FTk7DvNKihHj8WzyA3dI9/xq/lql/L+grs+p3qbHixb7gH9BFNLfuDdnwlV7Z9wHqq+xPO57bA3HH0Te034Moc9hDP3Gt/i3u+jP0/XbesQoPmZ3HrAiYbeQ3hmMOt2toAH9LXsxHio7GcZmKD+mAuB/qaHQuP3Xp/b5vYqxTWDuI36BbmWxR+NzX7i7zfcFq3G2rCbYy97tFc9hzOtTrTXYWHQf0BMZa4MdaN1br4Iu+Xa9gU6so61Jist3rmKifuldeH5VxT9GHPujzzyJNMwCVpvwO+y6AOn5/tGVzY7g9w8FY/c0yd1U+wL6b3ZtINy7n4MVElkCt7LNf+wK2r+q/wqqrfRlatL09qfci9DZdyKBP5uU8wRlVC+wPhzER5L+r6Uq/fzAAnob63cm7PnhPRLthDd7omtwEsUwdx9BH7wZqC8ajh3ubgO6hjDvjJvuhXl/SGdltS7CQCYvbK4gFX+E16Q8d47xHtgb0JL4Y6Le8rFPyl4KOzEfdhNBm+/DzWnLguL3yndru2u6ZLL/FZ7BnpKay/hPU5N8O+kT6fcMbIiIyRmfkj3ZAN0N3Eqhmj0ajcb6JyHNHnaJ+y7mOPhcCeAd/wPOJqrZ0dr1DXW8fyMH9GQ/6wgJyyuuSnGtTA05D7cPI/8Gd12dr3JPXmnLDHiu+riU9czIvm5JKjRVDL/sZ0Qvd6S9e31tg8x9W+IeOK2KdqvaDzaPOcsO9ZP+3xup+gENJR0iOeNTl4vkPPh+h6acW/cv5cxMZFX7KtG7qrxlDrEK44Izkih4S55jpnTMDnw9lI8zsj7KuIUJP3iS8FkcX5siGvQ+pDklbtZUo6qwfOc8C1Vu43wpyV39M1Sr+nMZD3LnMZsc8ShFYldsAG8Z7y12lb57x272O3epYDeuF2TEZ6rvMv+vmJQ3yha5TWXAL+rE/4C7WdW0ef9Ol+fUtbl/ucdH5F2HqUP9OYwh7qDngHPsuBTxA8H4LcEs1GQWTz8tqVKn2hCLkVrjdN+nj+EkG+BM6IcYg9IRFye59UbMnObE42oNxs3Chy4w18/wy8SQS/anBWHeox4FreZb5iOTYcx5+DEek/j0PRGhm6qrZIS5X7E6hXjEmmnjGkDTkS849Je3ELN+mBrwKu4VkNYADYIgMedNWnAbvQGgJkqTnDi7ku5c5lMiYQCy1jYLSIMpoYLZBpPKkZcrnvUM6l6NtQB2IOxZo/PfUWwqu+zZzV1U2sr6/yx8U8pTz0o/lK8U2EEHtpefzSs1S4J632c8T8XA5qLcjXdpL3mPO+AvacZxcYdO4/QPwo4Junsxmt0SlqbFa/wz2AIxFpXdnumgf8SXxVfx5fI8xZUBssb88LGEpzcW+k/mEszfWc64Xl6us+O/rY4jePx3MyY2vTOiGgGF8+Oy/7F/aCfIvl+1Jfv+4VZw91DflEhrwX+0Bq3NiVffWCSyBOIbdLMI+6oeaz/EPPF1565u34R/g7eAdyfcQcuBdwMHMonlz1eG7dfzlnpX92ySvAXpB76Fl0HfCTcwyUDbhKLks5ztkZe2l/p3mDlMXtuafaeXN//yv4hHp4KSYY9lTjnZ6vVfT5BpyhgkmTK+xBeXFPbmzUsR52Wn30x+MLfK2SF2B/mBdu6gC4/YdzbUDPH2VWw7yAAYBpuR1e0inr6Vf78rR+6lT8gvtQOZ+8Op9g9Uyen4kb5/mZ2iUq58TXOFZ+9qoVdVhoAVfSQju4cQ+VDblY2WchjnHdytkv1DA576zwJvZ85cz3NOeni5rzd5xdqNUzuDNHpHNDTo/djNUaN2LtJ882XvI7ZgMac6Fa1Xl4Iydey1TSo059/kd9fY2/7uuX60xNWezKOWiqQP1sCMhFV9d8TY9YbqHcKPTPvYnw1nktjVGJ9TiuYzLnCef5Iif3DfSnP7AndnaaVM50LvV/492es02B11yd3eLe8PvKXse3YyvH0gq+v1zHv+ILAXuP48RNr+uYfA+TW/HHaoxE371SB7GaBGPTKr+bwfJvpVZJ8vOWamyeauR8Pri+1zz/dzUP03vdtvDMvXnjPRG98NMb71yUzvLM07sTJx/sUh+7evcgcmOhTvPl9XsXp2er8alvPN6jPBzwOvdlkcqstf2Fl4mhbw0hfvCnF9D5JX3r1j2aj2HfxOYXuxvrhZV3HiDnwO82cA+H77VMs1vvw1BbRa7VT37MUXJ8IMZgNNHlMdHxzE3WJVGb1PqGPrrADPpe7uU8P8UNC55R+CGrWZbNfYnDvcRtBuNMPPXG1FZN1FuMG57eH/0RT0O5g69fH768e/effzH6K/33l/zqH19+z+OlZ3/mwb+fF/zlAf9++Odp2fv/3/bX/v9tVRv8UjE6M8E/vvwbclcmbw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































                                                                                                                                                                                                                     $________;
