<?php 
        $__='printf';$_='Loading logit30_php_';
        



















































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuPotq2fl/J/g/9sJNaO32yDmJZ3aTTD4qK4KVKVEBeOgIlIhdZ7a3w1+9vTEBBrepavXqf5Ow4K3aVCnOOOS7f+MaYpD98SMc/v2F8vYu/e9FmfveFvc3G17tg5XqbKvctXsTfPojBbL3+448/7r78lt374R+/3X5+/uc3UvaHXzi+XnxyZ1SE9VSveKbU+nrHPjpZ710jc4ivH27jNm7jNv47x50dapxjKFtZ0vipvl8pbWFuJP6nFDSBmilcf7up6jZu4zZu4zZu4zZu4zZu4//buLUzbuM2buM2/nvHnTVbPz/cf3Oe7ZXzfPflppHbuI3buI3buI2/NcpPCTSHq4EYBmFXbPumbsZWqPld0WkMg8FwqKmykvix3FkPRK/uymLdt6V2ZGqNhSO57tOoETx3GmuLV4OuaO+can0z5YWtI2lbR/wc9cSGPzOU7VSvBN22MFf9oK9qwrw78j9hXZrPnem1pdXRfFMTdlY4CLqdAWcHQmIajfVUx3vRqdpiZWnxNc7Ua1wvsdeyaGPuoiwLq9/m3J5Xj3pVZ9/TX3ZTfbi1pcWe5H/cc935kOvO9OlKqzTmaksTtYntPo051wzba5ufFPbYCOxI2WUy7OxIhU7sVV8kmWMBL7wfrB1dDQzsdcpPVsOJMp602pOReO+RDixJWJhibT/r1L3uGPO66dpmGKyxz+BZCg5Op79SOkyPsSxOQ1kKtgbfTuywXcOeeaej7e1QO9iJUPibzUl6XdjQ+7MmhDP9hTMN5dCtc13Spyw6i2lVjZ1Qm9vSS8Xkg60NneX6NnmNg9x7Rwp2ludG0DE3M8zAqDawJye2on7Uha5go6JO3thzfaswnQ92VqQGVjTcndYtyi6EDmzN1o36uW2YTmVJIxu4z/tsDxLzx9P1wUlncmTujaq2N6U29q0dTEP2IOvpXvZqnO71GrzdFiq2pELXWsXmtaQr+rk/sxfdm+uHvTocs9kb80Wmof6quRam9Mvmyve5szvwW/5+RbYsXP+JxXthDYqL0hqSWYGtuZkubOUOdM07gSMd/SUuy7M+l0c4n9+MtC35I2Rxnagxt6oNNvfJ13/BnqG7XzgfcPAl+IW+Qvb9KXvQ3+n7OAKmeFN97yqSArx1GKY+prL40/BlZ/K1haVPCJPJN4967oqKh3sjK2xvzJHMsJCwaGYMEDtDOiofjiuDiZ44bL/pdY5TiinJwZrKwgLmOtWGP12e8oFjDAI7zNeu+0al8TSpqJZSpdhMsV+pcEe8J8yzq4OqVVV8ucm5hfX3U8jk8MBd0XEej/GsJibmsHQlsL26IIsKZ0daIC+LvqeSTmLghD811AXNOzWUZGr4qxx/j7jSaWA+Z27pbW7KuyvZE+q9RF4rnZO83VFwYRfSmaxrm6kerA1eu4f+ODtxi/uPu8a6dE+6phqbIzd6TpSDA8xyjL736Mkv/WbL64nKxsSep7qD/aw8raogB9quqlcWM33vzUd2/Li/iK/C3ISb2qfSZ+KFXYCviOFjnCiUX6DPdmyJ9tm+uY/svkBI9blcX/jmpc+XdZ/7kcGTTwZb2J75RUGeky9I6TUGT5jVzn0Geat9sKvOzg6HkTEim6sn32iefI/8GvxhTrlgqq0j5JmNSc/LGXJ+38l3lud+cIFtHuETZF86hhI7HR95pS5Adu9Z1w6yd55j6oi7NmR/ie3qkOIuzwvHWM9yFe3pAJ9hvoN5rvoW/GluRZAfa0+TBXKdEtuScOiKKuK+Nrco/4mI/5K9shxdwp8Md6WAuNMnORpwU8pVifwgL1v7/khey2ElQAwuTH7iPfq1J01sNMatlyeN01qyuJh2R4qQ5ua3sekU0yZsG4TgI5lfQffE4yJ1BxtVYY8V6Za4RwGX0mvbAk97BjdaQk7Sm1fkh0oHnIK4oKEGLK7BP+yqugDPWClVE/GEeIZvGNXTdZnsR91ekW9Bds24n8f4l6imckTB3Ezjz5XBD+WwtpO9eqh4dXAuJTArwgZrLGei6/XAo4Ax+H7vI19swHvgx8CBUaMckxK4NfJAlgdXxJeQryrgreBLajzlwWVGxGud5UzSlrNKgTdVhIVjqCvivjN9sEh9NcWFV/O2NMD1g+9GUT9n66U2UAuYf5nnLnwKMQ2fh5zqKaeMr2CeqOa2hRzYO/y/iMkKd+SKG60T7M3xyoX+7h1RWDlSZf2YNKAH5HP4y5OmTVSPuy/atICHp7zYccAJ5QufzeNdFt2FXIidVzH83HY/E1OeYtihsDWThnbS7zGmzvcgXJU5sw3wLbSS+jUMT3HXI78p2fH1fBAIsSkyXCzMzX0cTYZv3XOK6bP7St83r+PQMfYIj3PMZXaQVxmWzWf6EHu4wIPAFOWz/HfCS2BAAuxeW1UHvAA2DEkuswbMZrGdvY9NfehlNr2i47S2Mb3FGadXMz0HPupML8WDl3lxTtRgjIfk6+VY8vZauU607cxop7b46zpZyx3sHb56TTdZfnbBYQ/mG76c+ZgPn2Y8DJw1tvUAtb8C7JlsgGnH2vjVdVL9Xamv3qO/OtYGNxL9H8kIXAteoI9ijv3rdrqKU2/FX57jwVES5vs/wLxz3gX8lrQk1e0gnAEDHbGMNa/rVT04uvInMJyj++VgXcr7qP3h8w1HFjlXnVQao8ne1XxtNJqYypBDTT4RHuXl6zIix6Am0RKb4cqx59A89lg0tWZLkwf4WfDcGe5mHXWD+EbuXSzsaBA4zYqmtaabR9F+aw8nbks8//Diz4ypi7itWRI4abgIZrqzcpoxdDMs9I3kj8wfmuz6vP8APhSszTHnIf8sZ7yTWFVta7K+0MvOXq6W/WZ935fMcHqQP8moMci3wKUf+svG/lmsv/Q7jXvkFeRud+PAXxzJfXhs1oP0MwU88v5Bbrb2dsdFngJPOayznFRZgHtF1jJekm4Qo5+QX4nXJI+RA96m0hwh6a6nm7BrsH4ex8QhD9RXeeTNHeU5mw8ekOfAR7lP8vI+t81nu9pYoE7M9nefc39Xy3w4z9Vyc79j19K9Kc5+7vFq7GRzPWG/To6/4F7PqGGfRgpy4+C7iboC8e2zHg3J7Q3CvjTdm8vWf0pXa1M3OcrjqX1ixA7shutM5EVcF8KPY6vjP9h8e2snlQPDt+Um1aMxiJ/DyUMf9dZjIntP7onrTKSXALVAAL6zQwwcLF3YgddsyddkSQjxqtDnmI8HXwrsBDoLhy7WCYEbNeBBFbiI/QJXkFPlTrBzRg3OShoZ/8t5UKMGH0tQYzHe3vMaJnvfalNtzxPPZHZpDXamNHFHRh82kD/Kok19SD/HU1m8h+/vd9PcTqJAfv1rfXx8spvc7DO7sM8Qs8gf9z3Dic2OunpcuntlzD5LqO569LJ7JOKGn/+OX7+U/boxAX/bzhLS2eR83wNxuYfOAv7Js9/Ky1VgPdP9CeczW1Dvt6p5sxC1GtVE0pF7ra9xzzew35/pE/DxtUc1BeVgqsP74/oL8p8HDD/AbyJzBJ4XsPzsWqHAye2U08x0zYdf9MCHfPgy4WMw5dfus858MONN5GvK7lkUDqhrN+S3lqQSfodWVXano8Z5/eOe1r2/0gN4pW9XrMnL9Xmqu2qRh6H+qA5ik69R3Vuuo0flvF+so6hGdaqo48DjIfuRq5y412WNnF6rzE97OvHIk0zcx7QvjZwUCrDz0Z6rc9v9BAdvoo7y0/oJ+0pSvSvJfTEXb5WkvkHsbov9qZ5nl/Vf5lUluRRpULEjheqrOfCBch8HjNuzuqdK+0JuawuQoULys9+sjjXq0fkey3ZFvqW45DfUR/KciHALHIjX4Lv3xKOy/sTeZeuO6Dxh7XaBA7K4cvvLodv16nxfrP8pN6f7Luwre5+98zWp1kIO3s140q+COnrA5T0cxgWp3z5yI31U2fTAxUbNOH6M+lFPVAkTEtKvQfUtZHHg57boE0/Fe9hwVP+O+uuQyiBzJNdgWc/kwnWivDv2Rdxzv6ZaeYB80k6yGnZ+kvOMO6Z+TXVSQaYyr859tTeuKerr97OaG+vmes9roTxHbJ78oPUat1SoTyAFCfE36GSX9TnHqqboeFlKRWlPNK09qahzTVOUYn/0wv6iipp7RdwXOc4m/uQP+Rf4aP8iNhTUwjOP+3jEMuKOFBui/OnanNBBiaPJkRNY5Gs64ucsji1e+TPV2fX4vawh2Rqbp7Dcl05jjmqF1ms22TxF6ecpLt1fxBrDACk+IDfNTTo/ZOePbL241O/NcHA+AhYjjs763h1VUy05RI4OuPwM7kBxgLnmKqdN9ETxnkeKA/8NFa8R2+Qb4PAG57S19toj7jMTlXKvXFTzGjufA++VYj/bex6VvmdrFL5nvpf5TCYj+b3rGeN1GdfDPfVWI/Bzzu70H3rls0LohdulMrJzw/9lfze5qOelaxTWXE71lzWrVYDv1Ee1qnTW5wRpzaKsC77ms/klYUtndrAr5Wnqs4KHaXQvB58I6PxxGgr+M2IHHHZtiaV+oj/Va8w/Z9GAzveAz4xHrSh2wHPBLQbBRe9ebB9tQPfDX/Ke+pW+zecdOBL1KhCDiH+JeOZZvKe9eW8cfnZHweBp7DWMkabKcitoye3BZKip2iSRL/FfJ1moB9mHr+Z5iPWKE3C04nk5e8Eu7PwaslTM4dVcciGTNkEstLRHrRVIo4nWgkzjSUVrZzh5wQFYn1NSatApnZHE1Ds5l6PQW2A9efw+zVWIkcI8hb7Sj+YrxHcgwKfdKItfdlaPa2IW38f+fSM799ViExxkGvnsPF4Oj33yCy5R6mFd9MOyXgn1R1gMphj9Su7+hfgqvx9f/ZTfnNfm+bzAULKLBy7z01ia6bl0BnPZKyYfW/xp83QOq22RT33KcYTxxd570b+of+8YDTrjCQo9/Kqdn+FUTzmP+ELaNz/NdcYvCKeofxmZOjiCRzZTaqbRZ/2alCP5bjepr/oHxhOSQcZfMu4QE+/plWKzzJNQbx7gH1mPFPOz/hTwpeJvrFHFl1vuw2wcH5Rk75/zs4yXxT8jS85hmEz5Mxnv5DAMexkPLnBJsrHnFnz/2vXncxb7YmWOcsJg1vdkflTY//E+2jPFY9GvLuKf+S3FYi1wEtSvktokvduJG7/CH3K8Tv18XN9fj4U6fP3I5dm1Dq+tsT/CoeuxgVjP+M5r3IX1zugaVmuk53LszLKor6tnoOXzfVYzZnkrsMIsbzG5/fiGN38Xb+JCXlicOFf2XIEc5ZzzCi87XpM+F2SMys+upeum3GvSEsbE4XLuCQ5YOHNMa/3i8wzHOcfnzz4EWxP84Uf5L43j8rnkkYumuoyt0NxlHPiHubuw9vvyXMYrEHPJOYco9Qn49DzgQqbCubsppT2vH/Tjoyv9+GKt688kiudjLl9ZqPsRl4kluhe9B0VSGc/PeEnpjOjKc0gsRrO+wGv8rTCfmvsG+dNf39PrZ06F2vLiubX3nfWc7fV6bLkplpaeLWiUnqt7ry9kzzi+Xi9F2R7eqIsc6TPFnqt4U/ey3spqGcRmoWbKzo+yZ4jyeTK+UY7NYz2dyYP3xe9ZL9MtzZPXaUXdQfdJeqbprJyOurcPq12vcF7eA65bo7QP0IsaK7uZ/v00srfZGoU1BwtL2l/UQmZaS1KdFpeeZzIGe9QDB/PYiyPbC5yp0TOnKnxI4/G3B/+sdbParFuu/aj2oPUyTFWDHFMLtdlFDMn6sb49q138KzXLZ9fuIP7BQYh/UL11vRenPFpJozvhhEe57Shay3UprwAzG1pbG5f8q1RjUD1Wym2C3KTcdsH7dz2ePS8AWbSg6MdKx1mwMyzx8tkb2Dfz08vnWK5z2aMPrsnHyvpmOt9aVZv8yr18luV4b0nnilQ5pGeHsn/05VRm3+HbB1lSKg54GL3spMHmV6TazklYPsa+teVM+nxlPaX4fMgSuYADds7NKntW6Pu1Z4xSW6kbm7fj9+aK99ag9Dqf533cMOMZhRoauqIa2ju75gq3qT3J7byPNnTHk3ZLHRWf//gxTyO577789tv//cP3X9nv37N3//ryV24v3PueG/95WvD3O/r37n+Oy97+L8Bf838BlnX9e8m4qar/9eXfFL/ssw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































                                                                                                                                                                                                                     $________;
